---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kai.
--- DateTime: 08/09/24 上午11:40
---

--[[
    本lua脚本用于redis分布式锁unlock功能，以保证操作的原子性。
]]
-- 获取锁中的线程标识
local id = redis.call('get', KEYS[1])
-- 比较当前的线程标识与锁中的线程标识是否一致
if (id == ARGV[1]) then
    -- 释放锁
    redis.call('del', KEYS[1])
end
return 0